### ISSUE TITLE
Add PUT method for /joke/:id

### ISSUE THREAD

**Issue by relia1** [pdx-cs-rust-web/knock-knock#6]
### Description:
Currently, our API allows for creating, retrieving, and deleting jokes, but not updating them. Adding the PUT functionality to the /joke/:id endpoint will updating existing jokes.

### Requirements
- The request should not allow for malformed request bodies
- Request URI needs to have an ID
- Return proper error codes for happy path and non happy path scenarios
- Requests with the same payload to the same joke id should have the same result

### Additional things to consider
With a PUT if the resource doesn't exist it should create it. This can possibly be handled by checking if a joke with the provided ID exists, and if it doesn't discard that ID and just create a new joke with the provided information.

**Comment by BartMassey** [comment]
Please describe the function of the PUT method: I assume this is for joke update?

PR is indeed welcome. Warning: SW is a moving target right now; it may take several iterations.

**Comment by relia1** [comment]
Made some updates to the ticket description. I'll probably update it more tomorrow morning.
